### ISSUE TITLE
Feature: User Dashboard

### ISSUE THREAD

**Issue by pooja-gera** [pooja-gera/connectify#2]
Create a user dashboard for a person to manage their teammates and hackathons. 

Reference Dashboard:
![image](https://github.com/pooja-gera/connectify/assets/55778515/2f6e24d1-b5ce-4776-94f7-720ad218d7ec)

Feature List:
- [ ] The user should be able to add the hackathons and their date via a calendar user interface
- [ ] The user should be able to add teammates to a hackathon from the list of teammates that they have matched with 
- [ ] The user should be able to add achievements to a hackathon
- [ ] The user should be able to see the list of teammates they have matched with 
- [ ] The dashboard should have a side navigation bar that allows the user to log out, navigate to the home, team selection and portfolio page

**Comment by kirti281003** [comment]
Hey, 
I would like to work on this issue
