### ISSUE TITLE
Feature: Portfolio Page

### ISSUE THREAD

**Issue by pooja-gera** [pooja-gera/connectify#3]
Create a portfolio page for people to share across all social media platforms as an irrefutable proof of work.
Make a form for the pre-registration and add the following details into the form:
- Name
- University
- Company
- Upload Image
- Social Media Links
    - Instagram
    - Facebook
    - Twitter
    - Linkedin
    - YouTube
    - GitHub
    - Medium 
    - Reddit
    - Twitch
    - Hashnode 
    - Hackernoon
- Projects Done
   - Project Title
   - GitHub Link
   - Technical Stack (Multi-Select)
   - Space for Writing about the Project
   - Live Project Link 
   - Images
- Volunteer / Speaker Involvements
   - Name of the Event
   - Organized By
   - Role (Speaker / Organizer / Volunteer etc.)
   - Date
   - Venue
   - Image
- A quote that defines you
- Select your username

Reference Diagram of Portfolio Page:
<img width="337" alt="Screenshot 2023-06-24 at 6 17 52 PM" src="https://github.com/pooja-gera/connectify/assets/55778515/9df83d83-14a3-4d11-9d2b-7904073a7c9b">
<img width="448" alt="Screenshot 2023-06-24 at 6 18 04 PM" src="https://github.com/pooja-gera/connectify/assets/55778515/d3550901-ec50-48ba-bb05-79d3c19e9d44">

**Comment by nisha-laur** [comment]
Hi Pooja di,

Thank you for opening this issue and providing the schema for the User Collection. I appreciate your effort in outlining the structure and fields for the User Collection. The schema you have shared seems to cover the essential information required for a user profile. It includes fields for basic details like name, university, company, and even allows for an image upload. The addition of the social media links, projects, and volunteer speaker involvements arrays provides a comprehensive view of a user's activities and contributions and I have tried to come up with the best suited solution to tackle this issue .



![portfolio11](https://github.com/pooja-gera/connectify/assets/104618576/d6aaf5b3-a0a0-4601-a87f-faa63e4b909e)
![portfolio22](https://github.com/pooja-gera/connectify/assets/104618576/c194b04d-de37-43f7-9a0b-ebc6046d4c08)


[myportfolio.pdf](https://github.com/pooja-gera/connectify/files/11857859/myportfolio.pdf)
